### ISSUE TITLE
Add to terraform module registry

### ISSUE THREAD

**Issue by mwarkentin** [indix/aws-maintenance-lambda#8]
It’d be nice to have this in the new official list of available modules: https://registry.terraform.io

**Comment by manojlds** [comment]
Nice suggestion. Is this something that you can help with a PR? If not, I will see what's involved in getting it there.

**Comment by mwarkentin** [comment]
Here are the docs: https://www.terraform.io/docs/registry/modules/publish.html

It sounds like it's based on the repo structure - so this might make more sense as a separate repo that somehow pulls the lambda stuff in? eg. `terraform-aws-maintenance-lambda`

I just noticed that your docs describe how to use terraform, but the `terraform` directory doesn't seem to exist?

**Comment by manojlds** [comment]
@mwarkentin I tried setting up as a module in the meantime already. The terraform folder was moved to this repo - https://github.com/indix/terraform-aws-maintenance-lambda

Had some issues creating module though, have raised an issue in the Terraform repo.

**Comment by mwarkentin** [comment]
@manojlds Cool! Took a quick look, and the structure of that repo looks ok to me based on the docs. Let me know if you get that sorted out. :)

**Comment by manojlds** [comment]
Here's the issue btw - https://github.com/hashicorp/terraform/issues/16198

Others are having the same issue as well.

**Comment by manojlds** [comment]
Was able to publish using a workaround - https://registry.terraform.io/modules/indix/maintenance-lambda/aws/0.5.0
